# Generated by Django 3.2 on 2021-05-17 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess_engine_web_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
