# Generated by Django 3.2 on 2021-05-25 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess_engine_web_app', '0003_game'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
