# Generated by Django 3.2 on 2021-05-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chess_engine_web_app', '0004_delete_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_color', models.CharField(max_length=5)),
                ('time', models.CharField(max_length=5)),
            ],
        ),
    ]
