# Generated by Django 3.2 on 2021-05-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_engine_web_app', '0005_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='move_number',
            field=models.IntegerField(default=0),
        ),
    ]
