# Generated by Django 3.2 on 2021-06-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_engine_web_app', '0006_game_move_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='fen',
            field=models.CharField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', max_length=100),
        ),
    ]
