# Generated by Django 3.2 on 2021-06-13 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess_engine_web_app', '0007_game_fen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='move_number',
        ),
        migrations.RemoveField(
            model_name='game',
            name='time',
        ),
    ]
